# Generated by Django 4.2 on 2023-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=80)),
                ('breed', models.CharField(max_length=80)),
                ('birth_date', models.DateTimeField()),
                ('entry_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('comments', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Cattle Info',
                'ordering': ['name'],
            },
        ),
    ]
