# Generated by Django 4.2 on 2023-07-19 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Cattle', max_length=80)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('gender', models.CharField(choices=[('Heifer', 'Heifer'), ('Bull', 'Bull'), ('Cow', 'Cow')], max_length=80)),
                ('breed', models.CharField(choices=[('Angus', 'Angus'), ('Crossbreed', 'Crossbreed')], max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('acquisition_method', models.CharField(blank=True, choices=[('Birth', 'Birth'), ('Purchase', 'Purchase'), ('Gift', 'Gift')], max_length=80, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('loss_method', models.CharField(blank=True, choices=[('Death', 'Death'), ('Sold', 'Sold'), ('Consumed', 'Consumed'), ('Gifted', 'Gifted')], max_length=80, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(max_length=2000)),
                ('deleted', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='cattle_pictures')),
            ],
            options={
                'verbose_name': 'Cattle Info',
                'verbose_name_plural': 'Cattle Info',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CattleMovementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=100)),
                ('field_size', models.FloatField(blank=True, null=True)),
                ('size_unit', models.CharField(blank=True, choices=[('ha', 'Ha'), ('ac', 'Ac')], max_length=2)),
                ('field_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, max_length=1200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='field_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='herd_pictures')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_herds', to='my_farm.field')),
                ('herd_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herd_leader', to='my_farm.cattle')),
            ],
        ),
        migrations.AddField(
            model_name='cattle',
            name='herd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_farm.herd'),
        ),
    ]
