# Generated by Django 4.2 on 2023-04-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cattle',
            options={'ordering': ['name'], 'verbose_name': 'Cattle Info', 'verbose_name_plural': 'Cattle Info'},
        ),
    ]
