# Generated by Django 4.2 on 2023-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0002_alter_cattle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
