# Generated by Django 4.2 on 2023-05-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0003_alter_cattle_birth_date_alter_cattle_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
