# Generated by Django 4.2 on 2023-05-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0004_alter_cattle_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
