# Generated by Django 4.2 on 2023-06-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0005_alter_cattle_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='acquisition_method',
            field=models.CharField(blank=True, choices=[('Birth', 'Birth'), ('Purchase', 'Purchase'), ('Gift', 'Gift')], max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='loss_method',
            field=models.CharField(blank=True, choices=[('Death', 'Death'), ('Sold', 'Sold'), ('Consumed', 'Consumed'), ('Gifted', 'Gifted')], max_length=80, null=True),
        ),
    ]
