# Generated by Django 4.2 on 2023-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0006_cattle_acquisition_method_cattle_loss_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquiredCattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Cattle', max_length=80)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('Heifer', 'Heifer'), ('Bull', 'Bull'), ('Cow', 'Cow')], max_length=80)),
                ('breed', models.CharField(max_length=80)),
                ('birth_date', models.DateField()),
                ('acquisition_method', models.CharField(choices=[('Purchase', 'Purchase'), ('Gift', 'Gift')], max_length=80)),
                ('entry_date', models.DateField()),
                ('loss_method', models.CharField(blank=True, choices=[('Death', 'Death'), ('Sold', 'Sold'), ('Consumed', 'Consumed'), ('Gifted', 'Gifted')], max_length=80, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Acquired Cattle',
                'verbose_name_plural': 'Acquired Cattle',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='OnFarmBirthCattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Cattle', max_length=80)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('Heifer', 'Heifer'), ('Bull', 'Bull'), ('Cow', 'Cow')], max_length=80)),
                ('breed', models.CharField(max_length=80)),
                ('birth_date', models.DateField()),
                ('acquisition_method', models.CharField(default='Birth', max_length=80)),
                ('loss_method', models.CharField(blank=True, choices=[('Death', 'Death'), ('Sold', 'Sold'), ('Consumed', 'Consumed'), ('Gifted', 'Gifted')], max_length=80, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'On Farm Birth Cattle',
                'verbose_name_plural': 'On Farm Birth Cattle',
                'ordering': ['number'],
            },
        ),
        migrations.DeleteModel(
            name='Cattle',
        ),
    ]
