# Generated by Django 4.2 on 2023-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0007_acquiredcattle_onfarmbirthcattle_delete_cattle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=80)),
                ('breed', models.CharField(max_length=80)),
                ('birth_date', models.DateField()),
                ('acquisition_method', models.CharField(blank=True, choices=[('Birth', 'Birth'), ('Purchase', 'Purchase'), ('Gift', 'Gift')], max_length=80, null=True)),
                ('entry_date', models.DateField()),
                ('loss_method', models.CharField(blank=True, choices=[('Death', 'Death'), ('Sold', 'Sold'), ('Consumed', 'Consumed'), ('Gifted', 'Gifted')], max_length=80, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Cattle Info',
                'verbose_name_plural': 'Cattle Info',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='AcquiredCattle',
        ),
        migrations.DeleteModel(
            name='OnFarmBirthCattle',
        ),
    ]
