# Generated by Django 4.2 on 2023-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0008_cattle_delete_acquiredcattle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='breed',
            field=models.CharField(choices=[('Angus', 'Angus'), ('Crossbreed', 'Crossbreed')], max_length=80),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='gender',
            field=models.CharField(choices=[('Heifer', 'Heifer'), ('Bull', 'Bull'), ('Cow', 'Cow')], max_length=80),
        ),
    ]
