# Generated by Django 4.2 on 2023-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0009_alter_cattle_breed_alter_cattle_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='type',
            field=models.CharField(default='Cattle', max_length=80),
        ),
    ]
