# Generated by Django 4.2 on 2023-06-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0010_alter_cattle_name_alter_cattle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
