# Generated by Django 4.2 on 2023-07-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0011_cattle_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattle',
            old_name='hidden',
            new_name='deleted',
        ),
    ]
