# Generated by Django 4.2 on 2023-07-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0012_rename_hidden_cattle_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cattle_pictures'),
        ),
    ]
