# Generated by Django 4.2 on 2023-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0013_cattle_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
