# Generated by Django 4.2 on 2023-07-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0016_alter_cattle_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
