# Generated by Django 4.2 on 2023-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0017_alter_cattle_birth_date_alter_cattle_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
