# Generated by Django 4.2 on 2023-07-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0018_alter_cattle_birth_date_alter_cattle_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CattleMovementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField()),
            ],
        ),
    ]
