# Generated by Django 4.2 on 2023-07-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0018_alter_cattle_birth_date_alter_cattle_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=100)),
                ('coordinates', models.CharField(max_length=100)),
                ('field_size', models.FloatField(blank=True, null=True)),
                ('size_unit', models.CharField(blank=True, choices=[('ha', 'Hectares'), ('ac', 'Acres')], max_length=2)),
                ('field_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='herd_pictures')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heard_field', to='my_farm.field')),
                ('herd_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herd_leader', to='my_farm.cattle')),
            ],
        ),
    ]
