# Generated by Django 4.2 on 2023-07-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0019_cattlemovementreport'),
        ('my_farm', '0019_field_herd'),
    ]

    operations = [
    ]
