# Generated by Django 4.2 on 2023-07-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0020_merge_0019_cattlemovementreport_0019_field_herd'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='herd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_farm.herd'),
        ),
        migrations.AddField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='field',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='field_pictures'),
        ),
        migrations.AlterField(
            model_name='herd',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_herds', to='my_farm.field'),
        ),
    ]
