# Generated by Django 4.2 on 2023-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_farm', '0022_alter_herd_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='field_pictures'),
        ),
    ]
